=== oxikran/src/ejercicio11/instituto.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="http://misitio.com" xmlns="http://misitio.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:ns="http://misitio.com" xmlns:hfp="http://www.w3.org/2001/XMLSchema-hasFacetAndProperty">
	<xs:element name="instituto">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="curso" maxOccurs="10">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="alumno" maxOccurs="30">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="nombre" type="xs:string" />
										<xs:element name="apellidos" type="xs:string" />
										<xs:element name="repetidor" type="xs:boolean" />
										<xs:element name="notas">
											<xs:complexType>
												<xs:sequence>
													<xs:group maxOccurs="10" ref="asignota" />
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="cial" type="xs:string" use="required" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="codigo" type="xs:int" use="required" />
						<xs:attribute name="nombre" type="xs:string" use="required" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="codigo" type="xs:int" use="required" />
			<xs:attribute name="nombre" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:group name="asignota">
		<xs:sequence>
			<xs:element name="asignatura" type="xs:string" />
			<xs:element name="nota">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="calif">
							<xs:attribute default="false" name="recuperacion"
								type="xs:boolean" />
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:group>
	<xs:simpleType name="calif">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="1" />
			<xs:maxInclusive value="10" />
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== oxikran/src/ejercicio11/instituto.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--New document created with EditiX at Thu Mar 08 09:22:30 WET 2012 -->


<?xml-stylesheet type="text/xsl" href="ejercicio11.xsl"?>


<mi:instituto codigo="38010700" nombre="IES Domingo Pérez Minik"
	xsi:schemaLocation="http://misitio.com instituto.xsd" xmlns:mi="http://misitio.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<curso codigo="1" nombre="1º ASIR">
		<alumno cial="A18X111">
			<nombre>Javier</nombre>
			<apellidos>Márquez fernández</apellidos>
			<repetidor>false</repetidor>
			<notas><!-- New document created with EditiX at Thu Mar 08 09:22:30 WET 
					2012 -->
				<asignatura>Lenguajes de marcas</asignatura>
				<nota recuperacion="true">8</nota>
				<asignatura>Redes</asignatura>
				<nota>7</nota>
				<asignatura>Fundamentos de hardware</asignatura>
				<nota>3</nota>
				<asignatura>Sistemas Operativos</asignatura>
				<nota>6</nota>
			</notas>
		</alumno>
		<alumno cial="A12B241">
			<nombre>Angel</nombre>
			<apellidos>Perez Fernández</apellidos>
			<repetidor>true</repetidor>
			<notas><!-- New document created with EditiX at Thu Mar 08 09:22:30 WET 
					2012 -->
				<asignatura>Lenguajes de marcas</asignatura>
				<nota recuperacion="false">3</nota>
				<asignatura>Redes</asignatura>
				<nota>3</nota>
				<asignatura>Fundamentos de hardware</asignatura>
				<nota>7</nota>
				<asignatura>Sistemas Operativos</asignatura>
				<nota>8</nota>
			</notas>
		</alumno>
		<alumno cial="D12X134">
			<nombre>Alba</nombre>
			<apellidos>Márquez Pérez</apellidos>
			<repetidor>false</repetidor>
			<notas><!-- New document created with EditiX at Thu Mar 08 09:22:30 WET 
					2012 -->
				<asignatura>Lenguajes de marcas</asignatura>
				<nota>5</nota>
				<asignatura>Redes</asignatura>
				<nota>9</nota>
				<asignatura>Fundamentos de hardware</asignatura>
				<nota>10</nota>
				<asignatura>Sistemas Operativos</asignatura>
				<nota>1</nota>
			</notas>
		</alumno>
		<alumno cial="Z23R762">
			<nombre>Luisa Fernanda</nombre>
			<apellidos>pérez Fernández</apellidos>
			<repetidor>false</repetidor>
			<notas><!-- New document created with EditiX at Thu Mar 08 09:22:30 WET 
					2012 -->
				<asignatura>Redes</asignatura>
				<nota>7</nota>
				<asignatura>Fundamentos de hardware</asignatura>
				<nota>5</nota>
				<asignatura>Sistemas Operativos</asignatura>
				<nota>6</nota>
			</notas>
		</alumno>
		<alumno cial="A27M242">
			<nombre>María</nombre>
			<apellidos>Álvarez Pérez</apellidos>
			<repetidor>true</repetidor>
			<notas>
				<asignatura>Lenguajes de programacion</asignatura>
				<nota>5</nota>
				<asignatura>Lenguajes de marcas</asignatura>
				<nota>5</nota>
				<asignatura>Redes</asignatura>
				<nota>5</nota>
				<asignatura>Fundamentos de hardware</asignatura>
				<nota>7</nota>
				<asignatura>Sistemas Operativos</asignatura>
				<nota>6</nota>
			</notas>
		</alumno>
	</curso>
	<curso codigo="1" nombre="1º DAM">
		<alumno cial="A38X100">
			<nombre>Ana</nombre>
			<apellidos>Barns Fernández</apellidos>
			<repetidor>false</repetidor>
			<notas><!-- New document created with EditiX at Thu Mar 08 09:22:30 WET 
					2012 -->
				<asignatura>Lenguajes de marcas</asignatura>
				<nota recuperacion="true">8</nota>
				<asignatura>Redes</asignatura>
				<nota>7</nota>
				<asignatura>Fundamentos de hardware</asignatura>
				<nota>3</nota>
				<asignatura>Sistemas Operativos</asignatura>
				<nota>6</nota>
			</notas>
		</alumno>
	
	</curso>	
</mi:instituto>
