=== oxikran/src/Oxikran/entregas/practica23.dtd
<!ENTITY % Contacto "Direccion, Telefono">
<!ELEMENT Estudiante (Centro | Alumno)+>
<!ELEMENT Alumno (Nombre, %Contacto;)>
<!ELEMENT Centro (Denominacion, %Contacto;)>
<!ELEMENT Nombre (#PCDATA)>
<!ELEMENT Denominacion (#PCDATA)>
<!ELEMENT Direccion (#PCDATA)>
<!ELEMENT Telefono (#PCDATA)>

=== oxikran/src/Oxikran/entregas/Practica23.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE Estudiante SYSTEM "practica23.dtd">
<Estudiante>
	<Centro>
		<Denominacion>I.E.S. Domingo PÃ©rez Minik</Denominacion>
		<Direccion>La Laguna</Direccion>
		<Telefono>922222222</Telefono>		
	</Centro>
	<Alumno>
		<Nombre>Joyce Rosario Batista</Nombre>
		<Direccion>Mi Casa</Direccion>
		<Telefono>666666666</Telefono>
	</Alumno>	
	<Alumno>
		<Nombre>Narciso Marrero Afonso</Nombre>
		<Direccion>Su casa</Direccion>
		<Telefono>666222666</Telefono>
	</Alumno>
</Estudiante>
